routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/vehicles/vehicles/{vehicle}","VehicleController@pass")->name("vehicles.pass");
Route::put("/transaction/transaction/{asset}","TransactionController@action")->name("transactions.action");
Route::get("/products/products/{product}","ProductController@auto_update")->name("products.auto");
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::delete("/carts/empty","CartController@empty")->name("carts.empty");


Route::get('/home', 'HomeController@index')->name('home');
Route::resource("categories","CategoryController");
Route::resource("products","ProductController");
Route::resource("carts","CartController");
Route::resource("vehicles","VehicleController");
Route::resource("transactions","TransactionController");

app/Vehicle.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vehicle extends Model
{
    public function product(){
    	return $this->belongsTo("App\Product");
    }
    public function asset_statuses()
	{
		return $this->belongsTo('App\AssetStatus');
	}
	public function assettransactions(){
    	return $this->belongsTo("App\AssetTransaction");
    }
}

app/Http/Controllers/VehicleController.php
<?php

namespace App\Http\Controllers;

use App\Vehicle;
use App\Product;
use App\Category;
use App\AssetStatus;
use DB;
use Session;
use Illuminate\Http\Request;

class VehicleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Vehicle $vehicle)
    {
        $this->authorize("view",$vehicle);
        $vehicles = Vehicle::all();
        $products = Product::all();
        $stock_count = Vehicle::count("id");
       
        if($stock_count > 0){
            $count_per_product = DB::table("vehicles")->select('product_id', DB::raw('count(*) as total'))->groupBy("product_id")->get();
            $count_avail = DB::table("vehicles")->select('product_id', DB::raw('count(*) as total'))->groupBy("product_id")->where("asset_status_id",1)->get();
            $not = ["asset_status_id" => 2,"asset_status_id" => 3];
            $count_not = DB::table("vehicles")->select('product_id', DB::raw('count(*) as total'))->groupBy("product_id")->where("asset_status_id",2)->orWhere("asset_status_id",3)->get();
            // dd(DB::table("vehicles")->select('product_id', DB::raw('count(*) as total'))->groupBy("product_id")->where("asset_status_id",2)->orWhere("asset_status_id",3)->get());
            // dd(count($count_not));
            if(count($count_avail) > 0){
                foreach($products as $product){   
                    foreach($count_avail as $avail){
                        if($product->id == $avail->product_id){
                            $result = Product::find($product->id);
                            $result->stocks_avail = $avail->total;
                            $result->save();

                            break;
                        }

                        if($product->id !== $avail->product_id){
                            $result = Product::find($product->id);
                            $result->stocks_avail = 0;
                            $result->save();

                        }
                    }    
                }
            }
            else{
                foreach($products as $product){
                    $product->stocks_avail = 0;
                    $product->save();
                }
            }

            if(count($count_not) > 0){
                foreach($products as $product){   
                    foreach($count_not as $nott){
                        if($product->id == $nott->product_id){
                            $result = Product::find($product->id);
                            $result->stocks_not_avail = $nott->total;
                            $result->save();

                            break;
                        }

                        if($product->id !== $nott->product_id){
                            $result = Product::find($product->id);
                            $result->stocks_not_avail = 0;
                            $result->save();

                        }
                    }    
                }
            }else{
                foreach($products as $product){
                    $product->stocks_not_avail = 0;
                    $product->save();
                }
            }
            if(count($count_per_product) > 0){
                foreach($products as $product){   
                    foreach($count_per_product as $countd){
                        if($product->id == $countd->product_id){
                            $result = Product::find($product->id);
                            $result->stocks = $countd->total;
                        // echo $product->id;
                            $result->save();
                        // $product->stocks = $countd->total;
                        // $product->save();
                        // echo $countd->product_id;
                        // echo $countd->total;
                            break;
                        }

                        if($product->id !== $countd->product_id){
                        // echo $product->id;
                            $result = Product::find($product->id);
                            $result->stocks = 0;
                            $result->save();

                        }



                // else if($product->id !== $countd->product_id){ 
                //     $product->stocks = 0;
                //     $product->save();
                //     // echo $product->id;
                // }
                // else{
                //     $product->stocks = 0;
                //     $product->save();
                //     // echo $product->id;
                // }
                    }    
                }
            }

        }
        else{
            foreach($products as $product){
                $product->stocks = 0;
                $product->stocks_avail = 0;
                $product->stocks_not_avail = 0;
                $product->save();
            }
        }

        
        
        $vehicles = Vehicle::all();
        $products = Product::all();
        foreach($products as $product){
            if($product->stocks <= 0){
                $product->stock_status_id = 3;
                $product->save();
            }
            else if($product->stocks_avail <= 0){
                $product->stock_status_id = 2;
                $product->save();
            }
            else{
                $product->stock_status_id = 1;
                $product->save();
            }
            // if($product->stocks_avail <= 0){
            //     $product->stock_status_id = 2;
            //     $product->save();
            // }
            // else if($product->stocks_avail > 0){
            //     $product->stock_status_id = 1;
            //     $product->save();
            // }
            // else{
            //     $product->stock_status_id = 3;
            //     $product->save();
            // }
        }
        return view("vehicles.index")->with("vehicles",Vehicle::all())->with("stock",$stock_count)->with("products",$products)->with("statuses",AssetStatus::all());
    //     $a = 0;
    //     foreach($countss as $countd){
    //         $a++;
    //         echo $a;
    //     }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Product $product)
    {
        if(Session::has("product")){
            $result = Session::get("product");
            $product = Product::find($result);
            return view("vehicles.create")->with("product",$product)->with("categories",Category::all());
        }else{
            return "no session";
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "plate-number" => "required|unique:vehicles,plate_number"
        ]);

        $vehicles = Vehicle::latest("asset_code_number")->first();

        // dd(isset($vehicles));

       if(isset($vehicles)){
            $codes = Vehicle::latest("asset_code_number")->first();
            $asset_number = $codes->asset_code_number;
            $asset_number++;
       }
       else{
            $code_array = [0,0,1];
            
            if($code_array[2] > 9){
                $code_array[2] = 0;
                $code_array[1] += 1;
            }

            $asset_number = "VHCL" . $code_array[0] . $code_array[1] . $code_array[2];
       }
        
        
        $product = Session::get("product");
        // dd($product);
        // dd($asset_number = "VHCL" . $code_array[0] . $code_array[1] . $code_array[2]);
        $vehicle = new Vehicle;
        $vehicle->plate_number = $request->input("plate-number");
        $vehicle->asset_code_number = $asset_number;
        $vehicle->product_id = $product;
        $vehicle->save();  

        return redirect(route("vehicles.index"));
        
        Session::forget("product");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function show(Vehicle $vehicle)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function edit(Vehicle $vehicle)
    {
        return dd($vehicle);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vehicle $vehicle)
    {
        $asset_status = $request->status;
        $vehicle->asset_status_id = $asset_status;
        $vehicle->save();

        return redirect(route("vehicles.index"));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Vehicle  $vehicle
     * @return \Illuminate\Http\Response
     */
    public function destroy(Vehicle $vehicle)
    {
        $vehicle->delete();
        return redirect(route("vehicles.index")); 
    }

    public function pass(Request $request, $vehicle)
    {
        $request->session()->put("product",$vehicle);
        return redirect(route("vehicles.create"));
    }
}

resources/views/vehicles/create.blade.php
@extends("layouts.app")
@section("content")
	<div class="container">
		<div class="jumbotron">
			<h2 class="text-center">Add Stock</h2>
		</div>
		<div class="row">
			<div class="col-12 col-md-8 col-lg-4 mx-auto">
				<div class="card" style="width: 18rem;">
					<img src="/public/{{$product->image}}" class="card-img-top" alt="...">
					<div class="card-body">
					<h5 class="card-title">{{$product->name}}</h5>
					<p class="card-text">&#8369;{{number_format($product->price,2)}}</p>
					<p class="card-text">{{$product->description}}</p>
					<p class="card-text"></p>
							@foreach($categories as $category)
							<p class="card-text">{{$product->category_id == $category->id ? "$category->name" : ""}}</p>
							@endforeach
				</div>
				<div class="card-footer">
					<form action="{{route("vehicles.store")}}" method="post">
						@csrf
						{{-- <input type="number" name="quantity" id="quantity" class="form-control mb-1" placeholder="quantity" min="1"> --}}
						<input type="text" name="plate-number" id="plate-number" class="form-control mb-1" placeholder="Plate Number">
						<button type="submit" class="btn btn-primary w-100">Add Stock</button>
					</form>
				</div>

				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/vehicles/index.blade.php
@extends("layouts.app")

@section("content")
	<div class="container">
		<div class="jumbotron">
			<h2 class="text-center">Vehicle Total Stocks: {{$stock}}</h2>
		</div>
		
			
			@foreach($products as $product)
			<div class="accordion" id="accordionExample">
				<div class="card">
					<div class="card-header" id="headingOne">
						<div class="row">
							<div class="col-12 col-md-8- col-lg-4">
								<h2 class="mb-0">
									<button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne{{$product->id}}" aria-expanded="true" aria-controls="collapseOne">
										<h2>{{$product->name}}</h2> 
									</button>
								</h2>
							</div>
							<div class="col-12 col-md-8 col-lg-8">
								<h6>No. of Stock: {{$product->stocks}}</h6>
								<h6>No. of Available Stock: {{$product->stocks_avail}}</h6>
								<h6>No. of Not Available Stock: {{$product->stocks_not_avail}}</h6>
							</div>
						</div>
						
					</div>

					<div id="collapseOne{{$product->id}}" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
						<div class="card-body">
							<div class="col-12">
								<div class="table-responsive">
									<table class="table table-striped">
										<tbody>
											@foreach($vehicles as $vehicle)
											@if($product->id == $vehicle->product_id)
											<tr>
												<td>Plate No.:</td>
												<td>{{$vehicle->plate_number}}</td>
												<td>Code No.:</td>
												<td>{{$vehicle->asset_code_number}}</td>
												<td>
													<form action="{{route("vehicles.update",["vehicle" => $vehicle->id])}}" method="post">
														@csrf
														@method("PUT")
														<select name="status" class="form-control mb-1">
															@foreach($statuses as $status)
															<option value="{{$status->id}}" {{$vehicle->asset_status_id == $status->id ? "selected" : ""}}>{{$status->name}}</option>
															@endforeach
														</select>
														<button class="btn btn-warning w-100">Set Status</button>
													</form>
												</td>
												<td>
													<form action="{{route("vehicles.destroy",["vehicle" => $vehicle->id])}}" method="post">
														@csrf
														@method("DELETE")
														<button class="btn btn-danger">Remove Vehicle</button>
													</form>
												</td>
											</tr>
											@else
											@endif
											@endforeach
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			@endforeach
			
			{{-- <div class="col-12 col-md-8 col-lg-3">
				
			</div> --}}
			
		
	</div>
@endsection