routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/vehicles/vehicles/{vehicle}","VehicleController@pass")->name("vehicles.pass");
Route::put("/transaction/transaction/{asset}","TransactionController@action")->name("transactions.action");
Route::get("/products/products/{product}","ProductController@auto_update")->name("products.auto");
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::delete("/carts/empty","CartController@empty")->name("carts.empty");


Route::get('/home', 'HomeController@index')->name('home');
Route::resource("categories","CategoryController");
Route::resource("products","ProductController");
Route::resource("carts","CartController");
Route::resource("vehicles","VehicleController");
Route::resource("transactions","TransactionController");

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;
use App\Product;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Product $product)
    {
        $this->authorize("view",$product);
        if(Session::has("cart")){
            $product_ids = array_keys(Session::get("cart"));
            $products = Product::find($product_ids);
            $total = 0;
            foreach($products as $product){
                $product->days = Session::get("cart.$product->id");
                $product->date = Session::get("cart-date.$product->id");
                for($x = 1;$x <= $product->days; $x++){
                    $product->date++;
                    $product->returndate = $product->date;
                }
                session()->put("cart-return.$product->id",$product->returndate);
                $product->date = Session::get("cart-date.$product->id");
                $product->subtotal = $product->days * $product->price;
                $total += $product->subtotal;
            }

            return view("carts.index")->with("products",$products)->with("total",$total);
        }else{
            return view("carts.index");
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            "days" => "required|min:1|max:5"
       ]);
        $request->validate([
            "date" => "required|date"
       ]);

       // $request->date++;
       // echo $request->date;
       $days = $request->days;
       $date = $request->date;
       // for($x = 1;$x <= $days; $x++){
       //      $date++;
       // }
       // echo $date;
       $request->session()->put("cart.$id",$days);
       $request->session()->put("cart-date.$id",$date);
       // dd( $request->session()->get("cart"));
       return redirect(route("carts.index"));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $request->session()->forget("cart.$id");
        if (count($request->session()->get("cart")) == 0){
            $request->session()->forget("cart");
        }
        return redirect(route("carts.index"))->with("status","Product removed from the cart");
    }

    public function empty(){
        Session::forget("cart");
        return redirect(route("carts.index"))->with("status","Cart is cleared");
    }
}

resources/views/carts/index.blade.php
@extends("layouts/app")
@section("content")

	<div class="container">
		<div class="row">
			<div class="col-12">
				<h3>My Request Cart</h3>
			</div>
			@if(Session::has("status"))
			<div class="col-12">
				<div class="alert alert-warning">
					{{Session::get("status")}}
				</div>
			</div>
			@endif
			{{-- @include("products.includes.error-status") --}}
			@if(Session::has("cart"))
			<div class="col-12">
				{{-- table --}}
				<div class="table-responsive">
					<table class="table table-striped table-hover text-center">
						<thead>
							<th scope="col">Name</th>
							<th scope="col">Rent Price Per Day</th>
							<th scope="col">No. of Days</th>
							<th scope="col">Date Needed</th>
							<th scope="col">Return Date</th>
							<th scope="col">Subtotal</th>
							<th scope="col">Action</th>
						</thead>
						<tbody>
							{{-- start of row --}}
							@foreach($products as $product)
							<tr>
								<th scope="row">{{$product->name}}</th>
								<td>&#8369;<span>{{number_format($product->price,2)}}</span></td>
								<form action="{{route("carts.update",["cart"=>$product->id])}}" method="post">
								<td>
									<div class="add-tocart-field mb-1">
										
											@csrf
											@method("PUT")
											<input type="number" name="days" value="{{$product->days}}" class="p-1 w-50" min="1" max="5">
											<button type="submit" class="btn btn-outline-secondary">Edit</button>
										
									</div>
								</td>
								<td>
									
										<input type="date" name="date" id="date" class="form-control" value="{{$product->date}}">
									
								</td>
								</form>
								<td>
									{{date("F d, Y", strtotime($product->returndate))}}
								</td>
								<td>&#8369;<span>{{number_format($product->subtotal,2)}}</span></td>
								<td>
									<form action="{{route("carts.destroy",["cart" => $product->id])}}" method="post">
										@method("DELETE")
										@csrf
										<button class="btn btn-danger w-100">Remove</button>
									</form>
								</td>
							</tr>
							@endforeach
							{{-- end of row --}}
						</tbody>
						<tfoot>
							<tr>
								<td colspan="4" class="text-right">Total</td>
								<td>&#8369;<span id="total">{{number_format($total,2)}}</span></td>
								<td>
									{{-- @can("isLogged") --}}
									<form action="{{route("transactions.store")}}" method="post">
										@csrf
										<div id="paypal-btn"></div>
										<button class="btn btn-primary w-100" type="submit">Submit Request</button>
									</form>
									{{-- @endcan
									@cannot("isLogged")
										<a href="{{route("login")}}" class="btn btn-success">Log In first</a>
									@endcan --}}
								</td>
							</tr>
						</tfoot>
					</table>
				</div>
				{{-- end of table --}}
				<form action="{{route("carts.empty")}}" method="post">
					@csrf
					@method("DELETE")
					<button type="submit" class="btn btn-outline-danger">Clear Request Cart</button>
				</form>
			</div>
			@else
				<div class="col-12">
					<div class="alert alert-info">
						Request Cart is Empty!
					</div>
				</div>
			@endif
		</div>
	</div>
	<script src="https://www.paypal.com/sdk/js?client-id=AZAifrojZxAvu0z3bgFtBfqzmHJHzWQ5jeP_lrlzEeIzUYYhIcck-hXgM8nVa5qoVPDDQ-CZttR1jTH6"></script>
@endsection